# Generated by Django 4.2.1 on 2023-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_dateTime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank='True', null=True, upload_to='images/')),
            ],
        ),
    ]
