# Generated by Django 4.2.1 on 2023-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_remove_userposts_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
