# Generated by Django 4.2.1 on 2023-05-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userposts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('issuing_country', models.CharField(max_length=3)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=3)),
                ('dob', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('doe', models.CharField(max_length=10)),
            ],
        ),
    ]
